
http-clients:
  internal:
    api-order-service-v1:
      base-url: http://localhost:50010/api/v1/orders
      timeout: 5s
    api-payment-service-v1:
      base-url: http://localhost:50020/api/v1/payments
      timeout: 5s
    api-payment-service-v2:
      base-url: http://localhost:50030/api/v1/payments
      timeout: 5s
    api-inventory-service-v1:
      base-url: http://localhost:50040/api/v1/inventories
      timeout: 5s
    api-inventory-service-v2:
      base-url: http://localhost:50050/api/v2/inventories
      timeout: 5s
    api-shipment-service-v1:
      base-url: http://localhost:50060/api/v1/shipment
      timeout: 5s
  external:
    api-visa-v1:
      base-url: http://localhost:52010/api/visa
      timeout: 5s
